---
server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  grpc_server_max_recv_msg_size: 1572864000
  grpc_server_max_send_msg_size: 1572864000

storage_config:
  aws:
    bucketnames: ${S3_BUCKET}
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    access_key_id: ${S3_ACCESS_KEY}
    secret_access_key: ${S3_SECRET_KEY}
    insecure: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true

memberlist:
  join_members:
    # You can use a headless k8s service for all distributor, ingester and querier components.
    - localhost:7946
ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  lifecycler:
    readiness_check_ring_health: false
    ring:
     kvstore:
      store: memberlist
    num_tokens: 128

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_
        period: 24h
table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
common:
  compactor_address: http://127.0.0.1:3100
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
