name: Build Grafana Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/grafana:latest
      working-directory: ./grafana
      
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.actor }}/grafana:latest
